### ISSUE TITLE
phantomjs

### ISSUE THREAD

**Issue by shaunc** [cagosta/requestAnimationFrame#9]
This doesn't seem to work for me in phantomjs. Is that simply not possible, or is it a bug? :)

**Comment by cagosta** [comment]
Hi, everything seems fine for me on Phantomjs 1.9.8 How does the bug happen for you ?

**Comment by shaunc** [comment]
I was trying to test `ember-collection`, which uses requestAnimationFrame, with phantomjs. We later went around `ember-collection`, so I don't have a small test case. (ember stuff is es6 so babel could have been affecting it as well). If you are interested I can try to boil this down when I have a free moment, or we can follow your inclination and leave it be until someone else hits it. :)
